[project]
name = "skellybot-analysis"
version = "0.1.0"
description = "A repo for the (python) code used to analyze data gathered from skellybot servers (mostly looking at student data from courses) "
readme = "README.md"
dependencies = [
    "discord>=2.3.2",
    "openai>=1.52.2",
    "pandas>=2.2.3",
    "pydantic[email]>=2.9.2",
    "python-dotenv>=1.0.1",
    "tiktoken>=0.8.0",
]
